# Generated by Django 5.0.6 on 2024-07-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_alter_automovil_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automovil',
            options={'ordering': ['modelo', 'marca', 'año'], 'verbose_name': 'Automovil', 'verbose_name_plural': 'Automoviles'},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['usuario'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Coompras'},
        ),
        migrations.AlterModelOptions(
            name='reseña',
            options={'ordering': ['usuario', 'puntuacion'], 'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'ordering': ['nombre', 'apellido'], 'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AlterField(
            model_name='automovil',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='puntuacion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
