# Generated by Django 5.0.6 on 2024-07-15 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_alter_automovil_options_alter_compra_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nro_Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_puntuacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='reseña',
            name='puntuacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.nro_puntuacion'),
        ),
    ]
