# Generated by Django 5.0.6 on 2024-07-15 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_nro_puntuacion_alter_reseña_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='puntuacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.nro_puntuacion'),
        ),
    ]
