# Generated by Django 5.0.6 on 2024-07-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0005_alter_reseña_puntuacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['usuario'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
    ]
