# Generated by Django 5.0.6 on 2024-07-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0006_alter_compra_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_de_usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
