# Generated by Django 5.0.6 on 2024-07-17 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0007_alter_compra_metodo_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodo_de_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='compra',
            name='metodo_pago',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.metodo_de_pago'),
        ),
    ]
