# Generated by Django 5.0.6 on 2024-07-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0012_alter_reseña_usuario_alter_compra_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovil',
            name='año',
            field=models.CharField(max_length=50),
        ),
    ]
