# Generated by Django 5.0.6 on 2024-07-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0015_cabina_cantidadpasajeros_freno_motor_traccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camioneta',
            name='capacidad_carga',
        ),
    ]
