# Generated by Django 5.0.6 on 2024-07-19 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0016_remove_camioneta_capacidad_carga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabina',
            old_name='cantidad',
            new_name='cabina',
        ),
        migrations.RenameField(
            model_name='freno',
            old_name='cantidad',
            new_name='freno',
        ),
        migrations.RenameField(
            model_name='motor',
            old_name='cantidad',
            new_name='motor',
        ),
        migrations.RenameField(
            model_name='traccion',
            old_name='cantidad',
            new_name='traccion',
        ),
        migrations.AddField(
            model_name='reseña',
            name='camioneta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.camioneta'),
        ),
        migrations.AddField(
            model_name='reseña',
            name='moto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.moto'),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='automovil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.automovil'),
        ),
        migrations.AlterUniqueTogether(
            name='reseña',
            unique_together={('usuario', 'automovil'), ('usuario', 'camioneta'), ('usuario', 'moto')},
        ),
    ]
