# Generated by Django 5.0.6 on 2024-07-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0017_rename_cantidad_cabina_cabina_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reseña',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='compra',
            name='camioneta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.camioneta'),
        ),
        migrations.AddField(
            model_name='compra',
            name='moto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.moto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='automovil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.automovil'),
        ),
    ]
