# Generated by Django 5.0.6 on 2024-07-19 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0018_alter_reseña_unique_together_compra_camioneta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraAutomovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automovil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.automovil')),
                ('metodoPago', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.metodo_de_pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='CompraCamioneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camioneta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.camioneta')),
                ('metodoPago', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.metodo_de_pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='CompraMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodoPago', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.metodo_de_pago')),
                ('moto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.moto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['usuario'],
            },
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
