# Generated by Django 5.0.6 on 2024-07-19 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0020_remove_compracamioneta_camioneta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='automovil',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.automovil'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='camioneta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.camioneta'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='moto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.moto'),
        ),
    ]
